import {
  Body,
  Controller,
  HttpCode,
  HttpStatus,
  Inject,
  Post,
  Req,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBody,
  ApiResponse,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import {
  EnableMfaRequestDto,
  GenerateMfaRequestDto,
  VerifyMfaDto,
} from '../dtos';
import { MFA_SERVICE } from '../tokens';
import { type IMfaService } from '../service';
import { type Request } from '../../../@types';
import { Public, SkipMfaSession } from '../decorators';
import { GuestGuard } from '../guards';

@ApiTags('Authentication', 'Multi-Factor Authentication')
@Controller('mfa')
export class MfaController {
  constructor(
    @Inject(MFA_SERVICE)
    private readonly mfaService: IMfaService,
  ) {}

  @Public()
  @SkipMfaSession()
  @UseGuards(GuestGuard)
  @Post('generate')
  @HttpCode(HttpStatus.OK)
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Returns MFA data to registry in authenticator apps',
  })
  @ApiBody({
    description: 'Temporary token obtained in the first step of authentication',
    type: GenerateMfaRequestDto,
  })
  @ApiUnauthorizedResponse({ description: 'Invalid credentials' })
  async generateMfa(@Body() body: GenerateMfaRequestDto) {
    const mfaData = await this.mfaService.generateMfa(body.tempToken);

    return {
      data: mfaData,
    };
  }

  @Public()
  @SkipMfaSession()
  @UseGuards(GuestGuard)
  @Post('enable')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Returns MFA data to registry in authenticator apps',
  })
  @ApiBody({
    description:
      'Temporary token obtained in the first step of authentication and code generated by the authenticator app',
    type: EnableMfaRequestDto,
  })
  @ApiUnauthorizedResponse({ description: 'Invalid credentials' })
  async enableMfa(@Body() body: EnableMfaRequestDto) {
    return await this.mfaService.verifyMfa(body.tempToken, body.code, true);
  }

  @Public()
  @SkipMfaSession()
  @Post('verify')
  @HttpCode(HttpStatus.OK)
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Success validating code',
  })
  @ApiBody({
    description:
      'Temporary token obtained in the first step of authentication and code generated by the authenticator app',
    type: VerifyMfaDto,
  })
  @ApiUnauthorizedResponse({ description: 'Invalid code' })
  async verifyMfa(@Req() req: Request, @Body() dto: VerifyMfaDto) {
    return await this.mfaService.verifyMfa(dto.tempToken, dto.code);
  }

  @SkipMfaSession()
  @Post('revalidate')
  @HttpCode(HttpStatus.OK)
  @ApiBody({
    description: 'Code generated by the authenticator app',
    type: VerifyMfaDto,
  })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Success validating code',
  })
  @ApiUnauthorizedResponse({ description: 'Invalid code' })
  async revalidateMfa(@Req() req: Request, @Body() dto: VerifyMfaDto) {
    return await this.mfaService.revalidateMfa(req.user.sub, dto.code);
  }
}
