version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_prisma
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: nest_prisma
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
