version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_prisma
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: nest_prisma
    volumes:
      - pgdata:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  pgdata:
