export const SPACE_SERVICE = Symbol('SPACE_SERVICE');
export const SPACE_REPOSITORY = Symbol('SPACE_REPOSITORY');

export const SPACE_MEMBER_SERVICE = Symbol('SPACE_MEMBER_SERVICE');
export const SPACE_MEMBER_REPOSITORY = Symbol('SPACE_MEMBER_REPOSITORY');
